spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter_db
    username: twitter_user
    password: twitter_password
    driverClassName: org.postgresql.Driver

#for testing auth security
logging:
  level:
    org:
      springframework:
        security: debug
