version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=twitter_user
      - POSTGRES_PASSWORD=twitter_password
      - POSTGRES_DB=twitter_db
    ports:
      - '5432:5432'